### ISSUE TITLE
가입신청 요청

### ISSUE THREAD

**Issue by deep-diver** [fast-ai-kr/signup-req#1]
가입신청을 원하시는 분은 자유롭게 댓글을 남겨 주시기 바랍니다. ("가입신청" 같이 무미건조한 말도 상관 없습니다)

**Comment by coffeedjimmy** [comment]
@deep-diver 

살포시 처음으로 가입신청 남겨봅니다!

**Comment by deep-diver** [comment]
@coffeedjimmy 감사합니다! 초대 보내 드렸습니당 :)

**Comment by kkweon** [comment]
@fast-ai-kr/admin 
가입신청합니다.

**Comment by archsyscall** [comment]
안녕하세요 가입요청합니다!

**Comment by yunh-kwak** [comment]
안녕하세요!
가입 신청드립니다.

**Comment by taegon** [comment]
@fast-ai-kr/admin
가입신청합니다.

**Comment by heewook** [comment]
안녕하세요?
@fast-ai-kr/admin
가입신청합니다.

**Comment by jin-sj** [comment]
안녕하세요~ 가입신청합니다
@fast-ai-kr/admin

**Comment by mukaman84** [comment]
안녕하세요~ 가입신청합니다.
@fast-ai-kr/admin

**Comment by Ign0reLee** [comment]
헉.. 저도 가능하면 도전하고 싶습니다..!
가입신청합니다.

@fast-ai-kr/admin

**Comment by PastelDew** [comment]
안녕하세요 가입신청합니다!

**Comment by bktsys** [comment]
Thank you :-)

**Comment by jhgeeyang** [comment]
가입신청 합니다

**Comment by kkweon** [comment]
Thank you for all your supports!

As it gets more difficult to manage manually, we switched to the PR based signup.

Please add your username to members.yaml according to
https://github.com/fast-ai-kr/signup-req#%EC%8B%A0%EC%B2%AD-%EB%B0%A9%EB%B2%95

Thanks.
